### ISSUE TITLE
Nach Wiederherstellung einer Sicherung -> Frontend und Backend nicht mehr erreichbar

### ISSUE THREAD

**Issue by emamil** [firegento/firegento-magesetup#224]
Ich wollte heute die Sicherung "Datenbank und Medien" von gestern wiederherstellen. 
Direkt darauf ist die Frontend-Seite und die Backend-Seite nicht mehr zu erreichen.
Wenn ich versuche in den Admin-Bereich zu gelangen, kommt diese Fehlerausgabe:

Fatal error: Class 'Zend_Uri_Exception' not found in /homepages/43/d582132361/htdocs/TestMagento/lib/Zend/Uri.php on line 140

Ich bitte um Unterstützung bei diesem Problem.

**Comment by sprankhub** [comment]
Please stick to English so that everyone can understand. Why do you think this has something to do with MageSetup? I do not see any correlation to our extension here.

As always, make sure to clear all caches and disable the compiler. [Magento Stack Exchange](https://magento.stackexchange.com/) is probably more suited for such questions.

**Comment by emamil** [comment]
Sorry, mein Fehler. Habe es auf die falsche Seite gepostet.
Thank you
