### ISSUE TITLE
SUPEE-6788 Developer Toolbox Error caused by Firegento

### ISSUE THREAD

**Issue by itsolon** [firegento/firegento-magesetup#237]
Hi, i encountered following error , the SUPEE-6788 Developer Toolbox script popups following error:
dont know if this is a Problem???

-------------------------------------------------------------------
---- SUPEE-6788 Developer Toolbox by ParadoxLabs ------------------
  https://github.com/rhoerr/supee-6788-toolbox
  Time: 2015-11-23T10:49:43+00:00
---- Loading whitelists -------------------------------------------
---- Searching config for bad routers -----------------------------
ERROR: Unable to load configuration: /var/www/vhosts/somedomain.com/httpdocs/app/code//FireGento/GermanSetup/etc/config.xml
---- Moving controllers for bad routers to avoid conflicts --------
---- Searching files for bad routes -------------------------------
---- Searching for whitelist problems -----------------------------
---- Summary ------------------------------------------------------
Affected Modules:

Affected Files:

Issues:
  Unable to load configuration: /var/www/vhosts/somedomain.com/httpdocs/app/code//FireGento/GermanSetup/etc/config.xml
See var/log/fixSUPEE6788.log for a record of all results.

**Comment by sprankhub** [comment]
I guess this is an issue of the toolbox. We disable the (old) extension `FireGento_GermanSetup` to make sure it is not used even though it is installed. In your case, it is not installed. The toolbox thinks it is installed, because it finds a corresponding tag. Hence, it searches for the corresponding `config.xml`, which it cannot find since the extension is not installed. That is why the error message occurs.

You can ignore this issue.
