### ISSUE TITLE
issue with saving revocation type

### ISSUE THREAD

**Issue by akkermanronald** [firegento/firegento-magesetup#244]
Using latest version, we have seen different installations of magesetup recently where the backend_type of revocation_product_type get's set to "int". In that case we are unable to save the revocation type with a product. Looking at a previous installation (without this issue) the backend_type is set to varchar and all works fine. Should the correct type be set as part of the installation script ?  

The backend type is not specified in the setup script mysql4-upgrade-2.1.1-2.2.0.php ?

**Comment by sprankhub** [comment]
The `revocation_product_type` is added in `src/app/code/community/FireGento/MageSetup/sql/magesetup_setup/mysql4-upgrade-2.1.1-2.2.0.php`. No backend / type is specified, so that `varchar` is used as a default, which should be okay. See https://github.com/OpenMage/magento-mirror/blob/f4b5f152af50e7a1da128b6a1f634658305ae72a/app/code/core/Mage/Eav/Model/Entity/Setup.php#L596:

    'backend_type'    => $this->_getValue($attr, 'type', 'varchar')

No idea how this could be `int` in your store. If you have any more information how this can be reproduced, feel free to re-open.
