### ISSUE TITLE
The "use Flat catalog product" option makes some attributes disappear

### ISSUE THREAD

**Issue by Anis108** [firegento/firegento-magesetup#247]
Can somebody please explain the following behavior:

When I set "Use Flat Catalog Product" to "no" all attributes appear.
The following happens while "Use Flat Catalog Product" is set to "yes"

After seting up the desired attributes to show in cart.
A few attributes are visible immedatily after saving "visible in cart" others dont appear directly.

The "others" appear while re-indexing is working throu the different indexes.
During this time all attributes that I setup become visible for a few minutes and disappears with out obvious reason.
Everything is still configured to show in cart.
Some attributes are still visible in the cart but "others" just disappear.
When I set "Use Flat Catalog Product" to "no" all attributes appear again.

Thanks in advance for your attention and help in the new 2016 :)

**Comment by sprankhub** [comment]
As you noticed, reindexing and clearing the cache is necessary after enabling the flat catalog. I do not see any reason why attributes should disappear in the cart after some time. You may want to check if your cronjob is set up properly.

Apart from that, this has nothing to do with MageSetup, so that I close this issue as offtopic. [Magento StackExchange](https://magento.stackexchange.com) may be a better place.
