### ISSUE TITLE
After installation, footer postponed - new things above the standard footer

### ISSUE THREAD

**Issue by Supermario72** [firegento/firegento-magesetup#313]
Hi...
After the installtion, the "Home Page" footer is postponed (has another look), like this

SEE BELOW

Can someone help?
THANKS

**Comment by Supermario72** [comment]
![footer](https://user-images.githubusercontent.com/32432067/31505910-3fb7f504-af76-11e7-8c36-b6b6bc4aef04.JPG)

**Comment by sprankhub** [comment]
This happens if you use the `rwd` theme, but somehow the MageSetup footer links template is taken from the `base` theme. Maybe you are using an old version of MageSetup (which does not have the `rwd` template). Check if you have the file `app/design/frontend/rwd/default/template/magesetup/footer/links.phtml` in your installation. If not, update MageSetup.
