### ISSUE TITLE
magesetup missing in packages repository

### ISSUE THREAD

**Issue by Hanmac** [firegento/firegento-magesetup#357]
this package is missing on repository:
https://packages.firegento.com/#magesetup

can that somehow be fixed?

**Comment by Schrank** [comment]
@sprankhub @mautz-et-tong https://github.com/magento-hackathon/composer-repository/pull/464

**Comment by Schrank** [comment]
@Hanmac Thanks!

**Comment by sprankhub** [comment]
@Schrank, actually, MageSetup was [already included](https://github.com/magento-hackathon/composer-repository/blob/840fe95e7beb9d7f821c08664ff7237872ca7da2/satis.json#L37). However, the package update failed due to unavailable packages (unfortunately, the generation breaks as soon as there is an unavailable package in the list). I removed these packages now and also removed the duplicate MageSetup entry again, see the [last commits](https://github.com/magento-hackathon/composer-repository/commits/master).

@Hanmac, the issue should be fixed.

**Comment by Schrank** [comment]
Be careful, you can't use connect20 packages, but must use the firegento/magesetup package.
